// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ContentBox: typeof import('./src/components/ContentBox.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FormLabel: typeof import('./src/components/FormLabel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCustomers: typeof import('./src/components/IconCustomers.vue')['default']
    IconDashboard: typeof import('./src/components/IconDashboard.vue')['default']
    IconTeam: typeof import('./src/components/IconTeam.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    ListBox: typeof import('./src/components/ListBox.vue')['default']
    PageHead: typeof import('./src/components/PageHead.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}

export { }
